###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.1
      container_name: nitflex-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=nitflex
        - MYSQL_USER=nitflex
        - MYSQL_PASSWORD=nitflex
      ports:
        - "8084:3306"

    webserver:
      image: nginx:alpine
      container_name: nitflex-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: nitflex-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

    db_admin:
      image: adminer
      links:
          - mariadb
      ports:
          - 8086:8080
