<?php

namespace AppBundle\Repository;

/**
 * PreferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreferRepository extends \Doctrine\ORM\EntityRepository
{
}
