<?php

namespace AppBundle\Repository;

/**
 * StudioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudioRepository extends \Doctrine\ORM\EntityRepository
{
}
